// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"a8zpazis25","name":"HeartRateCRUD","description":"","endpoint":"https://a8zpazis25.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/HeartRate","/HeartRate/123"]},{"id":"5gngw8e234","name":"StepCountCRUD","description":"","endpoint":"https://5gngw8e234.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/StepCount","/StepCount/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:abbdd26c-4457-4a80-ad7c-13a720eae43c',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'espertowatch-hosting-mobilehub-1699109079',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dshos6kvgq5ng.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"espertowatch-mobilehub-1699109079-Accounts","attributes":[{"name":"username","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"username"},{"tableName":"espertowatch-mobilehub-1699109079-StepCount","attributes":[{"name":"username","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"username"},{"tableName":"espertowatch-mobilehub-1699109079-HeartRate","attributes":[{"name":"username","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"username"}],
    'aws_mobile_analytics_app_id': '1c36350a634f41e281fe927704c825ec',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'a72c536a-8161-4dbd-933c-abb791dff6e8',
    'aws_project_name': 'EspertoWatch',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'espertowatch-deployments-mobilehub-1699109079',
    'aws_resource_name_prefix': 'espertowatch-mobilehub-1699109079',
}

export default awsmobile;
