// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"p9ttqy9ksc","name":"AccountsCRUD","description":"","endpoint":"https://p9ttqy9ksc.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/Accounts","/Accounts/123"]},{"id":"izogi4qs1b","name":"HeartRateCRUD","description":"","endpoint":"https://izogi4qs1b.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/HeartRate","/HeartRate/123"]},{"id":"ic9p4w71g5","name":"HeartRateGoalsCRUD","description":"","endpoint":"https://ic9p4w71g5.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/HeartRateGoals","/HeartRateGoals/123"]},{"id":"z5wacehxi6","name":"StepCountGoalsCRUD","description":"","endpoint":"https://z5wacehxi6.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/StepCountGoals","/StepCountGoals/123"]},{"id":"5gl4sr9612","name":"StepCountCRUD","description":"","endpoint":"https://5gl4sr9612.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/StepCount","/StepCount/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:120e83bd-2f65-4ceb-a078-1005578902ac',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'espertowatch-hosting-mobilehub-712314019',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3pvmykdnnur1w.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"espertowatch-mobilehub-712314019-StepCountGoals","attributes":[{"name":"username","type":"S"},{"name":"currentGoal","type":"N"},{"name":"goalHistory","type":"NS"},{"name":"isAutoset","type":"BOOL"}],"indexes":[],"region":"us-east-1","hashKey":"username"},{"tableName":"espertowatch-mobilehub-712314019-Accounts","attributes":[{"name":"username","type":"S"},{"name":"deviceAddress","type":"S"},{"name":"firstName","type":"S"},{"name":"lastName","type":"S"},{"name":"password","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"username"},{"tableName":"espertowatch-mobilehub-712314019-StepCount","attributes":[{"name":"username","type":"S"},{"name":"current","type":"N"},{"name":"dailySteps","type":"NS"}],"indexes":[],"region":"us-east-1","hashKey":"username"},{"tableName":"espertowatch-mobilehub-712314019-HeartRate","attributes":[{"name":"username","type":"S"},{"name":"current","type":"N"},{"name":"dailyHR","type":"NS"}],"indexes":[],"region":"us-east-1","hashKey":"username"},{"tableName":"espertowatch-mobilehub-712314019-HeartRateGoals","attributes":[{"name":"username","type":"S"},{"name":"currentGoal","type":"N"},{"name":"goalHistory","type":"NS"},{"name":"isAutoset","type":"BOOL"}],"indexes":[],"region":"us-east-1","hashKey":"username"}],
    'aws_mobile_analytics_app_id': '2f5eab9930f146668ed65ac91ff2d4ff',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'f84cd599-0be1-4049-93a4-77ad0aff6a95',
    'aws_project_name': 'EspertoWatch',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'espertowatch-deployments-mobilehub-712314019',
    'aws_resource_name_prefix': 'espertowatch-mobilehub-712314019',
}

export default awsmobile;
